### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by brownish** [loggur/baucis-decorator-deep-select#2]
After my last issue I've been having great success using deep-select. Today I just ran into an issue that I can't seem to figure out.

My schema:
```
 var SiteSchema = new mongoose.Schema({
    name: String,
    site_form: {
        descriptions: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }],
    }
 });

var SiteFormSchema = new Schema({
  type: {type: String},
  name: String,
  short_description: String,
  long_description: String,
  sites: [{ type: Schema.Types.ObjectId, ref: 'Site' }]
});
```

When I try to make a get request to api/v1/sites?select=name site_form.descriptions.name I get the error:
```/home/archadmin/maid/node_modules/mongoose/lib/schema.js:376
  if (obj == undefined) {
          ^
RangeError: Maximum call stack size exceeded
    at RegExp.test (native)
    at Schema.path (/home/archadmin/maid/node_modules/mongoose/lib/schema.js:381:26)
    at EmbeddedDocument.Document.$__path (/home/archadmin/maid/node_modules/mongoose/lib/document.js:797:24)
    at EmbeddedDocument.Document.get (/home/archadmin/maid/node_modules/mongoose/lib/document.js:760:21)
    at EmbeddedDocument.Object.defineProperty.get [as id] (/home/archadmin/maid/node_modules/mongoose/lib/document.js:1430:45)
    at gatherAllDocs (/home/archadmin/maid/node_modules/baucis-decorator-deep-select/index.js:86:10)
    at /home/archadmin/maid/node_modules/baucis-decorator-deep-select/index.js:95:7
    at Array.forEach (native)
    at gatherAllDocs (/home/archadmin/maid/node_modules/baucis-decorator-deep-select/index.js:94:9)
    at /home/archadmin/maid/node_modules/baucis-decorator-deep-select/index.js:99:7
    at Array.forEach (native)
    at gatherAllDocs (/home/archadmin/maid/node_modules/baucis-decorator-deep-select/index.js:98:22)
    at /home/archadmin/maid/node_modules/baucis-decorator-deep-select/index.js:95:7
    at Array.forEach (native)
    at gatherAllDocs (/home/archadmin/maid/node_modules/baucis-decorator-deep-select/index.js:94:9)
    at /home/archadmin/maid/node_modules/baucis-decorator-deep-select/index.js:99:7
    at Array.forEach (native)
    at gatherAllDocs (/home/archadmin/maid/node_modules/baucis-decorator-deep-select/index.js:98:22)
    at /home/archadmin/maid/node_modules/baucis-decorator-deep-select/index.js:95:7
    at Array.forEach (native)
    at gatherAllDocs (/home/archadmin/maid/node_modules/baucis-decorator-deep-select/index.js:94:9)
    at /home/archadmin/maid/node_modules/baucis-decorator-deep-select/index.js:99:7
```

Any thoughts?
Thanks!

**Comment by timbur** [comment]
My guess is that you have a circular reference within your data.  This is probably a bug with my code.  I'll create a patch that should hopefully prevent the infinite loop.

**Comment by timbur** [comment]
Alright try updating to v1.0.7 and let me know if it fixes it.  If not, there's probably some edge case I'm not considering.

**Comment by brownish** [comment]
Will do. Thanks

**Comment by brownish** [comment]
Tried it again, terminal output:
```
(null):0
(null)

RangeError: Maximum call stack size exceeded
```
I'm using the same data and schema I was using when I used regular deep-populate and that worked fine. Not sure what the issue is, deep-select works everywhere else.

**Comment by timbur** [comment]
Is there a circular reference with your data?  Can you show me the data and/or your full code?

**Comment by brownish** [comment]
Sorry for the late response.

Here's my full schema:
```
'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema,
    relationship = require("mongoose-relationship"),
    deepPopulate = require('mongoose-deep-populate');
 
 var SiteSchema = new mongoose.Schema({
    site_number: String,
    county: {type: Schema.Types.ObjectId, ref: 'County', childPath: 'sites'},
    number: Number,
    alpha: String,
    name: String,
    geometry: {
        type: {type: String},
        coordinates: []
    },
    site_form: {
        first_date: Number,
        date_survey: Date,
        field_number: String,
        acres: Number,
        descriptions: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }],
        functions: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }],
        mounds: Number,
        disturbance: {
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        },
        periods: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            confidence: String,
            original_text: String
        }],
        traditions: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            confidence: String,
            original_text: String
        }],
        contexts: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            confidence: String,
            original_text: String
        }],
        dating_methods: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }],
        ceramic_artifacts: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }],
        lithic_artifacts: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }],
        biological_artifacts: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }],
        other_artifacts: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }],
        exotic_artifacts: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }],
        major_drainage: {
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        },
        physiographic_settings: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }],
        owner_types: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }],
        work_types: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }],
        reference: String,
        change: String,
        national_register: {
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        },
        xnr: {
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        },
        cef: {
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        },
        sef: {
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        },
        doe: {
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        },
        burial_authenticated: {
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        },
        location_confidence: {
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        },
        in_date: Date,
        update: Date,
        notes: String,
        streg: {
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        },
        digitized: {
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        },
        alpha: Boolean,
        comments: String,
        data_region: {
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        },
        verified: Date,
        verified_by: String,
        updated: Date,
        editor: String,
        edit_date: Date,
        pwa_comment: String,
        georeferenced: Boolean,
        georeferenced_by: String,
        qaqc: Boolean,
        qaqc_by: String,
        scanned: Boolean,
        scanned_by: String,
        digitized_by: String,
        missing: Boolean,
        added: Boolean,
        added_by: String
    }
    
 });

var relationships = [
    'county',
    SiteSchema.path('site_form.functions').schema.path('value'),
    SiteSchema.path('site_form.descriptions').schema.path('value'),
    SiteSchema.path('site_form.periods').schema.path('value'),
    SiteSchema.path('site_form.traditions').schema.path('value'),
    SiteSchema.path('site_form.contexts').schema.path('value'),
    SiteSchema.path('site_form.dating_methods').schema.path('value'),
    SiteSchema.path('site_form.ceramic_artifacts').schema.path('value'),
    SiteSchema.path('site_form.lithic_artifacts').schema.path('value'),
    SiteSchema.path('site_form.biological_artifacts').schema.path('value'),
    SiteSchema.path('site_form.other_artifacts').schema.path('value'),
    SiteSchema.path('site_form.exotic_artifacts').schema.path('value'),
    SiteSchema.path('site_form.major_drainage.value'),
    SiteSchema.path('site_form.physiographic_settings').schema.path('value'),
    SiteSchema.path('site_form.owner_types').schema.path('value'),
    SiteSchema.path('site_form.work_types').schema.path('value'),
    SiteSchema.path('site_form.national_register.value'),
    SiteSchema.path('site_form.xnr.value'),
    SiteSchema.path('site_form.cef.value'),
    SiteSchema.path('site_form.sef.value'),
    SiteSchema.path('site_form.doe.value'),
    SiteSchema.path('site_form.burial_authenticated.value'),
    SiteSchema.path('site_form.location_confidence.value'),
    SiteSchema.path('site_form.streg.value'),
    SiteSchema.path('site_form.data_region.value')
    
    
    // 'site_form.functions.value',
    // 'site_form.disturbance.value',
    // 'site_form.periods.value',
    // 'site_form.traditions.value',
    // 'site_form.contexts.value',
    // 'site_form.dating_methods.value',
    // 'site_form.artifacts.ceramics.value',
    // 'site_form.artifacts.lithics.value',
    // 'site_form.artifacts.biological.value',
    // 'site_form.artifacts.other.value',
    // 'site_form.artifacts.exotic.value',
    // 'site_form.drainage.value',
    // 'site_form.physiographic_settings.value',
    // 'site_form.owner_types.value',
    // 'site_form.national_register.value',
    // 'site_form.xnr.value',
    // 'site_form.cef.value',
    // 'site_form.sef.value',
    // 'site_form.doe.value',
    // 'site_form.burial_authenticated.value',
    // 'site_form.location_confidence.value',
    // 'site_form.streg.value',
    // 'site_form.data_region.value'
    ];
SiteSchema.index({geometry: '2dsphere'});
SiteSchema.plugin(deepPopulate);
SiteSchema.plugin(relationship, {relationshipPathName: relationships});
module.exports = mongoose.model('Site', SiteSchema);
```

Here's the schema for the model I'm trying to populate:
```
'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var SiteFormSchema = new Schema({
  type: {type: String},
  name: String,
  short_description: String,
  long_description: String,
  sites: [{ type: Schema.Types.ObjectId, ref: 'Site' }]
});

module.exports = mongoose.model('SiteForm', SiteFormSchema);
```

I don't think there are any circular references in there. Although I've been looking at the code for so long it's very possible I've missed something. The schema is definitely garbage, but I wanted to, for the time being, keep the data structured pretty much as it was without making any changes.

**Comment by timbur** [comment]
Are you using both `mongoose-deep-populate` and `baucis-decorator-deep-select`?  I think the issue might be with the combination of modules, possibly `mongoose-relationship` as well.

**Comment by timbur** [comment]
Also, my deep population algorithm landed in `mongoose 4.1` so you will probably be able to upgrade to the latest `mongoose` without any issues.  See https://github.com/Automattic/mongoose/pull/3103.  :)

I'll update the dependencies of this package to reflect that right now while I'm thinking about it.

**Comment by timbur** [comment]
One more thing, to be clear, `mongoose-deep-populate` should no longer be necessary with `mongoose >= 4.1`

**Comment by brownish** [comment]
I am only using baucis-decorator-deep-select. I only had mongoose-deep-populate in there because i had a separate API I had prior to switching to baucis. I'll try your suggestions and let you know.
Thanks!

**Comment by timbur** [comment]
If you can create a repo that reproduces the issue, I should be able to narrow down it down.

**Comment by brownish** [comment]
Sounds good. I'll put something together.

**Comment by brownish** [comment]
Okay, check out https://github.com/brownish/deepselecterror

I think that reproduces my situation fairly well. Let me know if it works. I included sample data that automatically gets created when you run app.js

**Comment by timbur** [comment]
Thanks!  I'll check it out when I get a chance.  :)

**Comment by timbur** [comment]
Holy crap.  I've been busy.  Did you ever figure this out?  I should finally have time next week.

**Comment by brownish** [comment]
I wasn't able to figure it out. I ended up simplifying my schema by pulling some of the properties into another schema. I can, however, see myself trying to do the same type of selection in the future though, as I've got some pretty complex schema I'm working with. If you could take a look when you've got some time I'd greatly appreciate it.

**Comment by timbur** [comment]
Man I really dropped the ball on this one.  I meant to get back to it but got caught up with other things.  I also haven't used baucis in quite some time now.  What are you up to these days @brownish?  Are you still using this at all or have you moved onto other things?  There's a chance I will use baucis again in the near future, though it is unlikely, as I've learned a better way of doing things.  IIRC the main issue here was using too many different things for mongo/baucis at the same time, right?

**Comment by brownish** [comment]
@timbur Haha don't worry about it. I actually ended up switching to using graphql with rethinkdb instead of baucis and mongo.

**Comment by timbur** [comment]
Nice!  See you around!  😄
