### ISSUE TITLE
Unable to select arbitrary array fields

### ISSUE THREAD

**Issue by brownish** [loggur/baucis-decorator-deep-select#3]
I've got some arbitrary array fields in my schema like so:

```
let Schema = new mongoose.Schema({
  name: String,
  other_names: [String],
});
```

A get request to `/api/endpoint?select=name other_names`

returns the error:

```
{
  "status": 500,
  "name": "Internal Server Error",
  "message": "Cannot read property '0' of undefined (500).",
  "stack": "TypeError: Cannot read property '0' of undefined\n    at gatherPopulateParams (/home/archadmin/projects/maid-db/node_modules/baucis-decorator-deep-select/index.js:137:38)\n    at /home/archadmin/projects/maid-db/node_modules/baucis-decorator-deep-select/index.js:25:11\n    at Array.forEach (native)\n    at /home/archadmin/projects/maid-db/node_modules/baucis-decorator-deep-select/index.js:23:23\n    at Layer.handle [as handle_request] (/home/archadmin/projects/maid-db/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/archadmin/projects/maid-db/node_modules/express/lib/router/route.js:131:13)\n    at Route.dispatch (/home/archadmin/projects/maid-db/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/archadmin/projects/maid-db/node_modules/express/lib/router/layer.js:95:5)\n    at /home/archadmin/projects/maid-db/node_modules/express/lib/router/index.js:277:22\n    at Function.process_params (/home/archadmin/projects/maid-db/node_modules/express/lib/router/index.js:330:12)\n    at next (/home/archadmin/projects/maid-db/node_modules/express/lib/router/index.js:271:10)\n    at next (/home/archadmin/projects/maid-db/node_modules/express/lib/router/route.js:121:14)\n    at /home/archadmin/projects/maid-db/node_modules/baucis/Controller/request/streams.js:42:5\n    at Layer.handle [as handle_request] (/home/archadmin/projects/maid-db/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/archadmin/projects/maid-db/node_modules/express/lib/router/route.js:131:13)\n    at Route.dispatch (/home/archadmin/projects/maid-db/node_modules/express/lib/router/route.js:112:3)"
}
```

**Comment by timbur** [comment]
Wow I somehow completely missed this issue.  😓  I am so so sorry.  I only just now noticed it when checking all of the open issues under https://github.com/loggur.  It's been... what... 6 months?  I'm betting this particular issue is unimportant now.  Did you ever figure it out?
